// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAL27KkP-YFTynDiqwjYnYcrR4S1ywMQ',
    appId: '1:204974956557:web:577668d9ff4bac691fb544',
    messagingSenderId: '204974956557',
    projectId: 'damandu-59340',
    authDomain: 'damandu-59340.firebaseapp.com',
    storageBucket: 'damandu-59340.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP_1zixPwBQLm3gaXiKT7KcY6-V_gaSJo',
    appId: '1:204974956557:android:30081c523b2adcfb1fb544',
    messagingSenderId: '204974956557',
    projectId: 'damandu-59340',
    storageBucket: 'damandu-59340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBksvUf9g9UzDcnqFt_GUnhjqK5ts526Uc',
    appId: '1:204974956557:ios:71853ae3bf87e8731fb544',
    messagingSenderId: '204974956557',
    projectId: 'damandu-59340',
    storageBucket: 'damandu-59340.firebasestorage.app',
    iosBundleId: 'com.seonguk.damandu.damandu',
  );
}
